name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache pnpm packages
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build application
      run: pnpm build

    - name: Set lowercase repository name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set kubeconfig content
      run: |
        echo "KUBECONFIG_CONTENT<<EOF" >> $GITHUB_ENV
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Set context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ env.KUBECONFIG_CONTENT }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ../autocare360-infrastructure/deployment/kubernetes/base/namespace.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/configmap.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/secrets.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/app-deployment.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/app-service.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/db-deployment.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/base/db-service.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/network/ingress.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/volumes/mysql-pvc.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/RBAC/serviceaccount.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/RBAC/role.yaml \
                      -f ../autocare360-infrastructure/deployment/kubernetes/RBAC/rolebinding.yaml \
                      --namespace autocare360 \
                      --validate=false

    - name: Create Secrets
      run: |
        kubectl create secret generic autocare360-secrets --from-literal=db-url=${{ secrets.DB_URL }} --from-literal=jwt-secret=${{ secrets.JWT_SECRET }} --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} --from-literal=mysql-database=${{ secrets.MYSQL_DATABASE }} --from-literal=mysql-user=${{ secrets.MYSQL_USER }} --from-literal=mysql-password=${{ secrets.MYSQL_PASSWORD }} -n autocare360 --dry-run=client -o yaml | kubectl apply -f -